@Library('olcne-pipeline@status') _
import com.oracle.olcne.pipeline.BranchPattern

syslinuxImage = "olcne/ock:syslinux"
ocrImage = "container-registry.oracle.com/${syslinuxImage}"

imagePipeline(
  branchPattern: new BranchPattern(master: 'main', feature: '(?!^release/.*$)(^.*$)'),
  containers: ["${ocrImage}": "${syslinuxImage}"],
  platforms: ['ol8'],
  architectures: ['x86_64'],
  buildScript: "podman build -t ${ocrImage} ."
)
